version: "3.6"
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: YOUR_PASSWORD
  graphql-engine:
    image: hasura/graphql-engine:v2.37.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:YOUR_PASSWORD@postgres:5432/postgres
      DATABASE_URL: postgres://postgres:YOUR_PASSWORD@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: YOUR_KEY
      HASURA_GRAPHQL_JWT_SECRET: '{"key":"YOUR_KEY","type":"HS256","allowed_skew": 86400}'
volumes:
  db_data:
